```{r echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```


# Tests {#tests}

Tests are quite important to a healthy package. 

Some people even start off with tests! 😮 see [TDD, or "test driven development"](https://en.wikipedia.org/wiki/Test-driven_development)

## test infrastructure

Create manually, or run 


```r
usethis::use_testthat()
```

which:

- creates `tests/testthat.R`
- creates `tests/testthat/`
- adds `testthat` package as a Suggested package

## write some tests

Run 

```r
usethis::use_test('file-name')
```

Or create a file in `tests/testthat/` of the form `test-foobar.R`

Within the test file, if you ran `use_test()` you'll have something like:

```r
context("test-stuff")

test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})
```

Add a test like that above if you don't have it already. 

## structure of a test file

- `context` states the overall goal of the file, e.g., tests for function `helloworld`
    - `context`  can be repeated whenever you like
    - `context` are the things printed when you run tests
- `test_that` blocks, or function calls, can have any code run and at least one test expectation, e.g., `expect_equal`


## further reading

[the tests chapter](http://r-pkgs.had.co.nz/tests.html)
