--- 
title: "R package development workshop"
date: "`r paste0('built on ', Sys.Date())`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: PortlandRUserGroup/pkgdev
description: "R package development workshop"
---

# R package development

## Info

* Code: <https://github.com/PortlandRUserGroup/pkgdev/>
* Issues/Bug reports: <https://github.com/PortlandRUserGroup/pkgdev/issues>
* Workshop Materials: <http://portlandrusergroup.github.io/pkgdev/>

Packages

* `devtools`: <https://cran.rstudio.com/web/packages/devtools/>
* `testthat`: <https://cran.rstudio.com/web/packages/testthat/>
* `knitr`: <https://cran.rstudio.com/web/packages/knitr/>

## Installation

Stable version from CRAN

```{r eval=FALSE}
install.packages(c("devtools", "testthat", "knitr"))
```

Optionally:

```{r eval=FALSE}
devtools::install_github("metacran/mason.rpkg")
devtools::install_github("metacran/mason.github")
devtools::install_github("metacran/mason")

install.packages("usethis")
```
